"""empty message

Revision ID: 477456d2849d
Revises: 501aae8a9100
Create Date: 2024-11-26 21:07:35.286081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '477456d2849d'
down_revision = '501aae8a9100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setdata', schema=None) as batch_op:
        batch_op.alter_column('passwd',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setdata', schema=None) as batch_op:
        batch_op.alter_column('passwd',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
