"""empty message

Revision ID: 501aae8a9100
Revises: 
Create Date: 2024-11-24 21:55:01.690826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501aae8a9100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('mid', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('singer', sa.String(length=60), nullable=True),
    sa.Column('music_src', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('mid'),
    sa.UniqueConstraint('mid')
    )
    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_singer'), ['singer'], unique=False)

    op.create_table('select',
    sa.Column('mid', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('singer', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=True),
    sa.PrimaryKeyConstraint('mid'),
    sa.UniqueConstraint('mid')
    )
    with op.batch_alter_table('select', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_select_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_select_singer'), ['singer'], unique=False)

    op.create_table('setdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('U_key', sa.Text(), nullable=True),
    sa.Column('sit', sa.Text(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('passwd', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('theme', sa.Integer(), nullable=True),
    sa.Column('login_ok', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('setdata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setdata_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setdata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setdata_name'))

    op.drop_table('setdata')
    with op.batch_alter_table('select', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_select_singer'))
        batch_op.drop_index(batch_op.f('ix_select_name'))

    op.drop_table('select')
    with op.batch_alter_table('download', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_singer'))
        batch_op.drop_index(batch_op.f('ix_download_name'))

    op.drop_table('download')
    # ### end Alembic commands ###
